config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :mogis, :tracks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mogi.rb
class Mogi < ApplicationRecord
  belongs_to :mogi_type
  has_many :mogi_results
  accepts_nested_attributes_for :mogi_results
end

app/models/mogi_result.rb
class MogiResult < ApplicationRecord
  belongs_to :track
  belongs_to :mogi
end

app/models/mogi_type.rb
class MogiType < ApplicationRecord
  has_many :mogis
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :track_category
  has_many :mogi_results

  def increment_rank(value)
    case value
    when 1
      self.first += 1
    when 2
      self.second += 1
    when 3
      self.third += 1
    when 4
      self.fourth += 1
    when 5
      self.fifth += 1
    when 6 
      self.sixth += 1
    when 7 
      self.seventh += 1
    when 8 
      self.eighth += 1
    when 9 
      self.ninth += 1
    when 10 
      self.tenth += 1
    when 11 
      self.eleventh += 1
    when 12 
      self.twelfth += 1
    end
    save
  end

  def rank_ave()
    rank_count = [
      self.first,
      self.second, 
      self.third,
      self.fourth, 
      self.fifth,
      self.sixth,
      self.seventh, 
      self.eighth,
      self.ninth,
      self.tenth,
      self.eleventh,
      self.twelfth,
    ]
    race_sum = rank_count.sum
    rank = []
    rank_count.each_with_index do |count, index|
      rank << count * (index + 1)
    end
    rank_sum = rank.sum
    ave = (rank_sum / race_sum.to_f).round(2)
  end
end

app/models/track_category.rb
class TrackCategory < ApplicationRecord
  has_many :tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mogis_controller.rb
class MogisController < ApplicationController

  def index
    @mogis = Mogi.all
  end

  def show
    @mogis = Mogi.find(params[:id])
    @mogi_results = @mogis.mogi_results
  end

  def new
    @mogis = Mogi.new
    12.times { @mogis.mogi_results.build }
  end

  def create
    @mogis = Mogi.new(mogis_params)
    mogi_results_attributes = params.require(:mogi).permit(
      mogi_results_attributes: [:track_id, :rank]
      )[:mogi_results_attributes]
    if @mogis.save
      mogi_results_attributes_array = mogi_results_attributes.to_h.map do |index, attributes|
        track_id = attributes[:track_id]
        rank = attributes[:rank]
        track = Track.find(track_id)
        track.increment_rank(rank.to_i)
      end
      redirect_to mogi_path(@mogis)
    else
      puts @mogis.errors.full_messages
      render 'new'
    end
  end

  private

    def mogis_params
      params.require(:mogi).permit(:mogi_type_id, :total_score, :team_rank, :solo_rank, :url, mogi_results_attributes: [:track_id, :rank])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @mogis = Mogi.all
    @mogis_last = Mogi.order(created_at: :desc).limit(5)
    @mogi_results = MogiResult.all
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @tracks = Track.all
  end

  def show
    @tracks = Track.find(params[:id])
    @ave = @tracks.rank_ave
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mogis_helper.rb
module MogisHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <%= render 'shared/header' %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mogis/index.html.erb
<h1>Mogi List</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Link</th>
      <th>Team Rank</th>
      <th>Solo Rank</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <% @mogis.each.with_index(1) do |mogi, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= link_to "【#{mogi.mogi_type.name}】 #{mogi.created_at}", mogi_path(mogi) %></td>
        <td><%= mogi.team_rank %></td>
        <td><%= mogi.solo_rank %></td>
        <td><%= mogi.total_score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/mogis/new.html.erb
<h1>New Race</h1>

<%= form_with(model: @mogis, local: true) do |form| %>
  <div style="display: flex; align-items: center;">    
    <div>
      <%= form.collection_select(:mogi_type_id, MogiType.all, :id, :name, prompt: 'Select Mogi Type') %>

      <%= form.label :total_score %>
      <%= form.number_field :total_score %>

      <%= form.label :team_rank %>
      <%= form.number_field :team_rank %>

      <%= form.label :solo_rank %>
      <%= form.number_field :solo_rank %>

      <%= form.label :url %>
      <%= form.text_field :url %>

      <%= form.fields_for :mogi_results do |mogi_result_form| %>
        <div style="margin-bottom: 10px;">
          <%= mogi_result_form.collection_select :track_id, Track.all, :id, :name, prompt: 'Select Track' %>
          <%= mogi_result_form.number_field :rank, placeholder: 'Rank' %>
        </div>
      <% end %>
    </div>
  </div>

  <%= form.submit 'Create Race' %>
<% end %>

app/views/mogis/show.html.erb
<h1>Mogis Details</h1>
<h3>
  <a href="<%= @mogis.url %>" target="_blank">Lounge/TableDetails</a>
</h3>
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Score</th>
      <th>Team Rank</th>
      <th>Solo Rank</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @mogis.mogi_type.name %></td>
      <td><%= @mogis.total_score %> </td>
      <td><%= @mogis.team_rank %></td>
      <td><%= @mogis.solo_rank %></td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Track</th>
      <th>Rank</th>
    </tr>
  </thead>
  <tbody>
    <% @mogi_results.each.with_index(1) do |mogi_result, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= link_to mogi_result.track.name, track_path(mogi_result.track) %></td>
        <td><%= mogi_result.rank %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_header.html.erb
<header>
  <nav>
    <%= link_to 'Home', root_path %>
    <%= link_to 'Mogi List', mogis_path %>
    <%= link_to 'New Mogi', new_mogi_path %>
    <%= link_to 'Track List', tracks_path %>
    <a href="https://www.mk8dx-lounge.com/PlayerDetails/35714" target="_blank">Lounge</a>
  </nav>
</header>

app/views/static_pages/home.html.erb
<h2>Summary</h2>

<table>
  <thead>
    <tr>
      <th>Total Mogi</th>
      <th>Score Ave.</th>
      <th>Final Rank Ave.</th>
      <th>All Track Rank Ave.</th>
      <th>Max Score</th>
      <th>Min Score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @mogis.count %></td>
      <td><%= @mogis.average(:total_score).round(1) %></td>
      <td><%= @mogis.average(:solo_rank).round(1) %></td>
      <td><%= @mogi_results.average(:rank).round(1) %></td>
      <td><%= @mogis.maximum(:total_score) %></td>
      <td><%= @mogis.minimum(:total_score) %></td>
    </tr>
  </tbody>
</table>

<h2>History</h2>

<% @mogis_last.each do |mogi| %>
<h3>
<%= link_to "【#{mogi.mogi_type.name}】 #{mogi.created_at}", mogi_path(mogi) %>
</h3>
    <table>
    <thead>
      <tr>
        <th>Score</th>
        <th>Team Rank</th>
        <th>Solo Rank</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= mogi.total_score %> </td>
        <td><%= mogi.team_rank %></td>
        <td><%= mogi.solo_rank %></td>
      </tr>
    </tbody>
    <thead>
      <tr>
        <th>#</th>
        <th>Track</th>
        <th>Rank</th>
      </tr>
    </thead>
    <tbody>
      <% mogi.mogi_results.each.with_index(1) do |mogi_result, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= link_to mogi_result.track.name, track_path(mogi_result.track) %></td>
          <td><%= mogi_result.rank %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/tracks/index.html.erb
<h1>Track List</h1>

<ol>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
      </tr>
    </thead>
    <tbody>
      <% @tracks.each_slice(4).with_index do |group, index| %>
        <% if group.any? %>
          <tr>
            <th colspan="4"><%= group.first.track_category.name %>カップ</th>
          </tr>
        <% end %>
        <% group.each.with_index(1) do |track| %>
          <tr>
            <td><%= track.id %></td>
            <td><%= link_to track.name, track_path(track) %></td>
            <td><%= track.first %></td>
            <td><%= track.second %></td>
            <td><%= track.third %></td>
            <td><%= track.fourth %></td>
            <td><%= track.fifth %></td>
            <td><%= track.sixth %></td>
            <td><%= track.seventh %></td>
            <td><%= track.eighth %></td>
            <td><%= track.ninth %></td>
            <td><%= track.tenth %></td>
            <td><%= track.eleventh %></td>
            <td><%= track.twelfth %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</ol>

app/views/tracks/show.html.erb
<h1>Tracks Details</h1>
<h2><%= @tracks.name %></h2>
<table>
    <thead>
      <tr>
        <th>Ave.</th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @ave %></td>
        <td><%= @tracks.first %></td>
        <td><%= @tracks.second %></td>
        <td><%= @tracks.third %></td>
        <td><%= @tracks.fourth %></td>
        <td><%= @tracks.fifth %></td>
        <td><%= @tracks.sixth %></td>
        <td><%= @tracks.seventh %></td>
        <td><%= @tracks.eighth %></td>
        <td><%= @tracks.ninth %></td>
        <td><%= @tracks.tenth %></td>
        <td><%= @tracks.eleventh %></td>
        <td><%= @tracks.twelfth %></td>
      </tr>
    </tbody>
  </table>